name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9.0.5
      - uses: actions/setup-node@v4
        with:
          node-version: '20.12.0'
          cache: 'pnpm'
          cache-dependency-path: gui/package-lock.json
      - run: pnpm install
      - run: pnpm run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          cname: schedule-diary.com
          force_orphan: true
