name: Deploy GUI to GitHub Pages

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.5

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.0'
          cache-dependency-path: 'gui/pnpm-lock.yaml'

      - name: Installing packages
        run: pnpm install

      - name: Building GUI
        run: pnpm run build

      - name: Publish GUI to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gui/dist
          force_orphan: true
